boot: bootm: use null character instead of NULL
This fixes the following compiler error:

`boot/bootm.c:1002:83: error: assignment to ‘char’ from ‘void *’ makes
integer from pointer without a cast [-Wint-conversion]`